@startuml
title クラス図

class 走行モード
Class 目標軌道
class 目標速度
class エンコーダー
class 目標角速度
class ジャイロ
class 補正モード
class IRセンサ
class 探索ロジック
class 最短経路導出ロジック
class 速度制御方式
class 角速度制御方式
class モータ
class 走行ログ


@enduml


走行モード：走行モードにより目標軌道の生成方法が変わるため。
目標軌道：マウスの移動経路の目標が必要であるため。
目標速度：目標軌道の生成には目標速度が必要となるため
エンコーダー：現在の速度を知るために必要
目標角速度；目標軌道の生成には目標角速度が必要となるため
ジャイロ：現在の角速度を知るために必要。
補正モード：目標軌道に追従するとき、補正方法を都度変更するため必要
IRセンサ：一部補正モードにおいて、壁との距離を知るために必要
探索ロジック：一部走行モードにおいて、目標軌道の生成に必要。
最短経路導出ロジック：一部走行モードにおいて、目標軌道の生成に必要。
速度制御：目標速度に対し、速度を追従させるために必要
角速度制御：目標角速度に対し、角速度を追従させるために必要
走行ログ：走行時のログを記録、出力するために必要