@startuml
title クラス図

class 走行モード
走行モード : 現在のモード名

Class 目標軌道
目標軌道 : 目標速度
目標軌道 : 目標角速度 
目標軌道 : 状態

class エンコーダ

class ジャイロ


class マウス状態
マウス状態 : 距離
マウス状態 : 角度
マウス状態 : 速度
マウス状態 : 角速度


class 動き方
動き方 : 状態

class 印加電圧調整
印加電圧調整 : 状態

class 軌道補正
軌道補正 : 補正モード
軌道補正 : 横壁補正
軌道補正 : 前壁補正

class IRセンサ
IRセンサ : 前距離
IRセンサ : 横距離

class 探索ロジック
探索ロジック : 壁情報

class 最短経路導出ロジック
最短経路導出ロジック : 壁情報

class 軌道制御
軌道制御 : 速度制御
軌道制御 : 角速度制御

class モータ


class 走行ログ
走行ログ : 記録
走行ログ : 出力


走行モード <|-- マウス状態 : 速度によるSW

走行モード -- 探索ロジック : 探索モード

走行モード -- 最短経路導出ロジック : 最短モード

最短経路導出ロジック -- 動き方 : 移動先指定
最短経路導出ロジック o-- 動き方 : 移動完了

探索ロジック -- 動き方 : 移動先指定
探索ロジック --o 動き方 : 壁情報
探索ロジック o-- 動き方 : 移動完了

動き方 -- 目標軌道 

動き方 -- 軌道補正 : 前壁制御

目標軌道 --o 軌道制御

軌道制御 -- 印加電圧調整 : 偏差による印加電圧

軌道補正 -- 印加電圧調整 : 壁補正による印加電圧

軌道補正 -- 軌道制御 : 横壁補正時、角度制御のI項処理を変化

印加電圧調整 -- モータ : 印加電圧

IRセンサ -- 軌道補正 : 壁距離

マウス状態 -- 軌道制御

IRセンサ --|> 探索ロジック : 壁の有無

マウス状態 -- エンコーダ

マウス状態 -- ジャイロ

軌道補正 --o マウス状態 : 壁切れによる補正

マウス状態 -- 目標軌道 : 位置補正を目標軌道に反映



@enduml


走行モード：走行モードそのもの、責務として、競技者の入力に応じてモードを変更する。
目標軌道：マウスの移動経路の目標。責務として、走行モードに応じた目標軌道から、目標速度、目標角速度を生成する。
エンコーダー：責務として、現在の速度を取得する
ジャイロ：責務として、現在の角速度を取得する。
補正モード：補正モードそのもの、責務として、モータ印加電圧の補正方法（ジャイロ？IRせんさ？）を決定する。
IRセンサ：現在の壁との距離、壁の有無を取得する。
探索ロジック：迷路の探索経路の生成。責務として、目標軌道の生成、及び壁情報の記録
最短経路導出ロジック：最短走行。責務として、壁情報をもとに最短経路を生成。
軌道制御：軌道の制御方法。責務として、目標速度、角速度に対する、現在速度、角速度をもとに、モータ印加電圧を決定する。
軌道補正：軌道の補正方法。責務として、補正モードをもとにIRセンサの情報からモータ印加電圧を補正する。
モータ：モータそのもの。責務として、補正モードに応じ、電圧をモータに印加する。
走行ログ：ログシステム。責務として、走行時のログを記録し、出力する。


**クラス候補**
走行モード：走行モードにより目標軌道の生成方法が変わるため。
目標軌道：マウスの移動経路の目標が必要であるため。
目標速度：目標軌道の生成には目標速度が必要となるため
エンコーダー：現在の速度を知るために必要
目標角速度；目標軌道の生成には目標角速度が必要となるため
ジャイロ：現在の角速度を知るために必要。
補正モード：目標軌道に追従するとき、補正方法を都度変更するため必要
IRセンサ：一部補正モードにおいて、壁との距離を知るために必要
探索ロジック：一部走行モードにおいて、目標軌道の生成に必要。
最短経路導出ロジック：一部走行モードにおいて、目標軌道の生成に必要。
速度制御：目標速度に対し、速度を追従させるために必要
角速度制御：目標角速度に対し、角速度を追従させるために必要
走行ログ：走行時のログを記録、出力するために必要