/*
 * ICM20648_Registor.h
 *
 *  Created on: Jul 14, 2019
 *      Author: 岡田 泰裕
 */

#ifndef ICM20648_REGISTOR_H_
#define ICM20648_REGISTOR_H_

/*!
	@brief	ICM-20648のレジスタを列挙します。
*/

// USER BANK
#define REG_USER_BANK_0 		(0b00000000)
#define REG_USER_BANK_1 		(0b00010000)
#define REG_USER_BANK_2 		(0b00100000)
#define REG_USER_BANK_3 		(0b00110000)

// USER BANK0 REGISTER MAP
#define WHO_AM_I				(0)
#define USER_CTRL				(3)
#define LP_CONFIG				(5)
#define PWR_MGMT_1				(6)
#define PWR_MGMT_2				(7)
#define INT_PIN_CFG				(15)
#define INT_ENABLE				(16)
#define INT_ENABLE_1			(17)
#define INT_ENABLE_2			(18)
#define INT_ENABLE_3			(19)
#define I2C_MST_STATUS			(23)
#define INT_STATUS				(25)
#define INT_STATUS_1			(26)
#define INT_STATUS_2			(27)
#define INT_STATUS_3			(28)
#define DELAY_TIMEH				(40)
#define DELAY_TIMEL				(41)
#define ACCEL_XOUT_H			(45)
#define ACCEL_XOUT_L			(46)
#define ACCEL_YOUT_H			(47)
#define ACCEL_YOUT_L			(48)
#define ACCEL_ZOUT_H			(49)
#define ACCEL_ZOUT_L			(50)
#define GYRO_XOUT_H				(51)
#define GYRO_XOUT_L				(52)
#define GYRO_YOUT_H				(53)
#define GYRO_YOUT_L				(54)
#define GYRO_ZOUT_H				(55)
#define GYRO_ZOUT_L				(56)
#define TEMP_OUT_H				(57)
#define TEMP_OUT_L				(58)
#define EXT_SLV_SENS_DATA_00	(59)
#define EXT_SLV_SENS_DATA_01	(60)
#define EXT_SLV_SENS_DATA_02	(61)
#define EXT_SLV_SENS_DATA_03	(62)
#define EXT_SLV_SENS_DATA_04	(63)
#define EXT_SLV_SENS_DATA_05	(64)
#define EXT_SLV_SENS_DATA_06	(65)
#define EXT_SLV_SENS_DATA_07	(66)
#define EXT_SLV_SENS_DATA_08	(67)
#define EXT_SLV_SENS_DATA_09	(68)
#define EXT_SLV_SENS_DATA_10	(69)
#define EXT_SLV_SENS_DATA_11	(70)
#define EXT_SLV_SENS_DATA_12	(71)
#define EXT_SLV_SENS_DATA_13	(72)
#define EXT_SLV_SENS_DATA_14	(73)
#define EXT_SLV_SENS_DATA_15	(74)
#define EXT_SLV_SENS_DATA_16	(75)
#define EXT_SLV_SENS_DATA_17	(76)
#define EXT_SLV_SENS_DATA_18	(77)
#define EXT_SLV_SENS_DATA_19	(78)
#define EXT_SLV_SENS_DATA_20	(79)
#define EXT_SLV_SENS_DATA_21	(80)
#define EXT_SLV_SENS_DATA_22	(81)
#define EXT_SLV_SENS_DATA_23	(82)
#define FIFO_EN_1				(102)
#define FIFO_EN_2				(103)
#define FIFO_RST				(104)
#define FIFO_MODE				(105)
#define FIFO_COUNTH				(112)
#define FIFO_COUNTL				(113)
#define FIFO_R_W				(114)
#define FIFO_RDY_STATUS			(116)
#define FIFO_CFG				(118)
#define REG_BANK_SEL			(127)

// USER BANK1 REGISTER MAP
#define SELF_TEST_X_GYRO		(2)
#define SELF_TEST_Y_GYRO		(3)
#define SELF_TEST_Z_GYRO		(4)
#define SELF_TEST_X_ACCEL		(14)
#define SELF_TEST_Y_ACCEL		(15)
#define SELF_TEST_Z_ACCEL		(16)
#define XA_OFFSET_H				(20)
#define XA_OFFSET_L				(21)
#define YA_OFFSET_H				(22)
#define YA_OFFSET_L				(23)
#define ZA_OFFSET_H				(26)
#define ZA_OFFSET_L				(27)
#define TIMEBASE_CORRECTION_PLL	(40)
#define REG_BANK_SEL			(127)

// USER BANK2 REGISTER MAP
#define GYRO_SMPLRT_DIV			(0)
#define GYRO_CONFIG_1			(1)
#define GYRO_CONFIG_2			(2)
#define XG_OFFS_USRH			(3)
#define XG_OFFS_USRL			(4)
#define YG_OFFS_USRH			(5)
#define YG_OFFS_USRL			(6)
#define ZG_OFFS_USRH			(7)
#define ZG_OFFS_USRL			(8)
#define ODR_ALIGN_EN			(9)
#define ACCEL_SMPLRT_DIV_1		(16)
#define ACCEL_SMPLRT_DIV_2		(17)
#define ACCEL_INTEL_CTRL		(18)
#define ACCEL_WOM_THR			(19)
#define ACCEL_CONFIG			(20)
#define ACCEL_CONFIG_2			(21)
#define FSYNC_CONFIG			(82)
#define TEMP_CONFIG				(83)
#define MOD_CTRL_USR			(84)
#define REG_BANK_SEL			(127)

// USER BANK3 REGISTER MAP
#define I2C_MST_ODR_CONFIG		(0)
#define I2C_MST_CTRL			(1)
#define I2C_MST_DELAY_CTRL		(2)
#define I2C_SLV0_ADDR			(3)
#define I2C_SLV0_REG			(4)
#define I2C_SLV0_CTRL			(5)
#define I2C_SLV0_DO				(6)
#define I2C_SLV1_ADDR			(7)
#define I2C_SLV1_REG			(8)
#define I2C_SLV1_CTRL			(9)
#define I2C_SLV1_DO				(10)
#define I2C_SLV2_ADDR			(11)
#define I2C_SLV2_REG			(12)
#define I2C_SLV2_CTRL			(13)
#define I2C_SLV2_DO				(14)
#define I2C_SLV3_ADDR			(15)
#define I2C_SLV3_REG			(16)
#define I2C_SLV3_CTRL			(17)
#define I2C_SLV3_DO				(18)
#define I2C_SLV4_ADDR			(19)
#define I2C_SLV4_REG			(20)
#define I2C_SLV4_CTRL			(21)
#define I2C_SLV4_DO				(22)
#define I2C_SLV4_DI				(23)
#define REG_BANK_SEL			(127)



#endif /* ICM20648_REGISTOR_H_ */
